

insert_job = dict(
    indeedKey="2343224234",
    title='Awesome Job',
    company="ABC Company",
    url="https://my-awesome-company.com/the-job-description",
    contactName="Sam Smith",
    contactPhone="518-999-9099",
    contactEmail="test@abccompany.com",
    description="T" * 1100,
    isRemote=True,
    employmentType="Full Time",
    careerLevel="Executive",
    compensation="100,000 USD",
    travelPercentage=50,
    securityClearanceReq=True,
    securityType="TS/SCI",
    dataSource="gjm",
    searchTerm="gis",
    # location
    city="Saratoga Springs",
    state="NY",
    countryCode="us",
    lat=-74.163878,
    lon=40.809562,
    tags=['qgis'],
    categories=['software-engineer', 'entry-level'],
)

insert_job_2 = dict(
    indeedKey="2343224234",
    title='Awesome Job',
    company="ABC Company",
    url="https://my-awesome-company.com/the-job-description",
    contactName="Sam Smith",
    contactPhone="518-999-9099",
    contactEmail="test@abccompany.com",
    description="T" * 1100,
    isRemote=True,
    employmentType="Full Time",
    careerLevel="Junior",
    compensation="100,000 USD",
    travelPercentage=50,
    securityClearanceReq=True,
    securityType="TS/SCI",
    dataSource="indeed",
    searchTerm=None,
    # location
    city="Saratoga Springs",
    state="NY",
    countryCode="us",
    lat=-74.163878,
    lon=40.809562,
    tags=['qgis'],
    categories=['software-engineer', 'entry-level'],
)
